# Generated by Django 5.2.15 on 2026-07-04 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleep_started_at', models.DateTimeField()),
                ('wake_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Imported')], default='MANUAL', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sleep_started_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('wake_at__isnull', True)), fields=('user',), name='one_open_sleep_session_per_user')],
            },
        ),
    ]
