# Generated by Django 5.2.15 on 2026-07-06 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('stage', models.CharField(choices=[('SEED', 'Seed'), ('CAMP', 'Camp'), ('HAMLET', 'Hamlet'), ('VILLAGE', 'Village'), ('TOWN', 'Town'), ('THRIVING_TOWN', 'Thriving Town')], default='SEED', max_length=24)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='village_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('HABIT', 'Habit completion'), ('TASK', 'Task completion'), ('SLEEP', 'Completed sleep session')], max_length=16)),
                ('source_id', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
                ('life_area', models.CharField(choices=[('LEARNING', 'Learning'), ('HEALTH', 'Health'), ('SLEEP', 'Sleep'), ('CAREER', 'Career'), ('MINDFULNESS', 'Mindfulness'), ('CREATIVITY', 'Creativity'), ('RELATIONSHIPS', 'Relationships'), ('PERSONAL_GROWTH', 'Personal Growth'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-event_date', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'source_id'), name='unique_village_reward_source')],
            },
        ),
        migrations.CreateModel(
            name='VillageBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_key', models.CharField(choices=[('LIBRARY', 'Library'), ('FARM', 'Farm'), ('HEARTH', 'Hearth'), ('OBSERVATORY', 'Observatory'), ('GARDEN', 'Garden'), ('WORKSHOP', 'Artisan Workshop'), ('TOWN_SQUARE', 'Town Square'), ('CENTRAL_TREE', 'Central Tree'), ('WINDMILL', 'Windmill')], max_length=24)),
                ('life_area', models.CharField(choices=[('LEARNING', 'Learning'), ('HEALTH', 'Health'), ('SLEEP', 'Sleep'), ('CAREER', 'Career'), ('MINDFULNESS', 'Mindfulness'), ('CREATIVITY', 'Creativity'), ('RELATIONSHIPS', 'Relationships'), ('PERSONAL_GROWTH', 'Personal Growth'), ('OTHER', 'Other')], max_length=24)),
                ('domain_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_buildings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('building_key',),
                'constraints': [models.UniqueConstraint(fields=('user', 'building_key'), name='unique_user_village_building')],
            },
        ),
        migrations.CreateModel(
            name='VillageUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlock_key', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('DECORATION', 'Decoration'), ('ANIMAL', 'Animal'), ('AREA', 'Area'), ('ATMOSPHERE', 'Atmosphere')], max_length=16)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-unlocked_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'unlock_key'), name='unique_user_village_unlock')],
            },
        ),
    ]
