# Generated by Django 5.2.16 on 2026-07-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardevent',
            name='event_type',
            field=models.CharField(choices=[('HABIT', 'Habit completion'), ('DAILY', 'Daily completion'), ('TASK', 'Task completion'), ('SLEEP', 'Completed sleep session')], max_length=16),
        ),
    ]
