# Generated by Django 5.2.15 on 2026-07-04 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_habits', models.PositiveIntegerField(default=0)),
                ('completed_habits', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_snapshot')],
            },
        ),
    ]
