# Generated by Django 5.2.16 on 2026-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_minutes_before',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='schedule_mode',
            field=models.CharField(choices=[('SELECTED_DAYS', 'Selected days'), ('WEEKLY_TARGET', 'Number of days per week')], default='SELECTED_DAYS', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
