# Generated by Django 5.2.16 on 2026-07-08 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('life_area', models.CharField(choices=[('LEARNING', 'Learning'), ('HEALTH', 'Health'), ('SLEEP', 'Sleep'), ('CAREER', 'Career'), ('MINDFULNESS', 'Mindfulness'), ('CREATIVITY', 'Creativity'), ('RELATIONSHIPS', 'Relationships'), ('PERSONAL_GROWTH', 'Personal Growth'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('start_date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('daily', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='dailies.daily')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='dailies.daily')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('daily', 'date'), name='unique_daily_completion_date')],
            },
        ),
    ]
