# Generated by Django 5.2.15 on 2026-07-04 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('life_area', models.CharField(choices=[('LEARNING', 'Learning'), ('HEALTH', 'Health'), ('SLEEP', 'Sleep'), ('CAREER', 'Career'), ('MINDFULNESS', 'Mindfulness'), ('CREATIVITY', 'Creativity'), ('RELATIONSHIPS', 'Relationships'), ('PERSONAL_GROWTH', 'Personal Growth'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('IMPORTANT', 'Important')], default='NORMAL', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('completed', 'due_date', '-created_at'),
            },
        ),
    ]
