# Generated by Django 5.2.16 on 2026-07-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('completed', 'due_at', 'due_date', '-created_at')},
        ),
        migrations.AddField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_minutes_before',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=12),
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=12)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='tasks.task')),
            ],
        ),
    ]
